Repository UnicornGlobal/lumen-cashier, pull requests merged in 2019-11, with the labels that each got.

#1 Lumen Compatibility
  .gitignore
  .travis.yml
  CHANGELOG.md
  LUMEN.md
  README.md
  composer.json
  config/cashier.php
  phpunit.xml.dist
  routes/web.php
  src/Billable.php
  src/Cashier.php
  src/CashierServiceProvider.php
  src/Exceptions/IncompletePayment.php
  src/Exceptions/InvalidStripeCustomer.php
  src/Exceptions/PaymentActionRequired.php
  src/Exceptions/PaymentFailure.php
  src/Exceptions/SubscriptionUpdateFailure.php
  src/Http/Controllers/PaymentController.php
  src/Http/Controllers/WebhookController.php
  src/Http/Middleware/VerifyWebhookSignature.php
  src/Invoice.php
  src/InvoiceItem.php
  src/Logger.php
  src/Notifications/ConfirmPayment.php
  src/Payment.php
  src/PaymentMethod.php
  src/Subscription.php
  src/SubscriptionBuilder.php
  tests/Fixtures/Auth/User.php
  tests/Fixtures/User.php
  tests/Integration/ChargesTest.php
  tests/Integration/CustomerTest.php
  tests/Integration/IntegrationTestCase.php
  tests/Integration/InvoicesTest.php
  tests/Integration/LoggerTest.php
  tests/Integration/PaymentMethodsTest.php
  tests/Integration/SubscriptionsTest.php
  tests/Integration/VerifyWebhookSignatureTest.php
  tests/Integration/WebhooksTest.php
  tests/TestCase.php
  tests/Unit/CustomerTest.php
  tests/Unit/InvoiceTest.php
  tests/Unit/PaymentTest.php
  tests/Unit/SubscriptionTest.php
  tests/Unit/WebhookControllerTest.php
Labels: size/XL, 🔍 Ready for Review

#2 Fix failing tests
  .travis.yml
  LUMEN.md
  README.md
  composer.json
  phpunit.xml.dist
  routes/web.php
  src/CashierServiceProvider.php
  src/Http/Controllers/WebhookController.php
  tests/Integration/IntegrationTestCase.php
  tests/Integration/LoggerTest.php
  tests/Integration/WebhooksTest.php
  tests/TestCase.php
  tests/Unit/WebhookControllerTest.php
Labels: size/M, 🔍 Ready for Review

#3 Update readme
  README.md
Labels: size/XS, 🔍 Ready for Review
